### PR TITLE
[PATCH v4] api: pktio: allow inline inbound to be enabled only if IPsec config is done

### PR DESCRIPTION
**Pull request by anoobj**

### CODE REVIEW

**Comment by JannePeltonen** [comment]
If we add this restriction, it would still be ok to do the following steps:

- open a pktio with inline IPsec disabled
- receive packets through the pktio
- configure IPsec with inbound inline enabled
- close the pktio
- open the pktio with inline IPsec enabled

**Comment by anoobj** [comment]
> 
> 
> If we add this restriction, it would still be ok to do the following steps:
> 
>     * open a pktio with inline IPsec disabled
> 
>     * receive packets through the pktio
> 
>     * configure IPsec with inbound inline enabled
> 
>     * close the pktio
> 
>     * open the pktio with inline IPsec enabled
> 
> 
> Would this be ok in your implementation?

Yes. That should be fine.

**Comment by JannePeltonen** [comment]
Looks ok to me.

The API text appears also in doc/users-guide/users-guide-pktio.adoc. It would be good to change the text there too. It probably needs to be a separate commit to keep API commits clean from other stuff.

**Review by JannePeltonen — APPROVED** [review]

**Comment by anoobj** [comment]
@JannePeltonen There was a typo in the commit header of the last patch. v4 is to address that.

**Comment by JannePeltonen** [comment]
> There was a typo in the commit header of the last patch. v4 is to address that.

v4 looks ok.

**Pull request merged**
