### PR TITLE
[PATCH v1] test: packet_gen: fix error check for less rounds

### PR DESCRIPTION
**Pull request by nithind1988**
Fix error check for case when total tx packets is
less than MIN_RX_PACKETS_CI.

Signed-off-by: Nithin Dabilpuram <ndabilpuram@marvell.com>

### CODE REVIEW

**Review by JereLeppanen — COMMENTED** [review]
I suppose this would be fine. But since this only affects the exit code, for CI, what is the actual benefit of this change?

**Comment by nithind1988** [comment]
> 
> 
> I suppose this would be fine. But since this only affects the exit code, for CI, what is the actual benefit of this change?

It is needed for CI tests one of our simulators, where we cannot run default number of rounds i.e 500.

**Comment by JereLeppanen** [comment]
> It is needed for CI tests one of our simulators, where we cannot run default number of rounds i.e 500.

Don't you need to modify the packet_gen parameters as well? And don't you have similar problems with other tests?

**Comment by nithind1988** [comment]
> 
> 
> > It is needed for CI tests one of our simulators, where we cannot run default number of rounds i.e 500.
> 
> Don't you need to modify the packet_gen parameters as well? And don't you have similar problems with other tests?

That parameter we are overriding using our platform specific pktio_env and a wrapper script around odp_packet_gen

**Comment by JereLeppanen** [comment]
> That parameter we are overriding using our platform specific pktio_env and a wrapper script around odp_packet_gen

I see, thanks for the explanation.

But on second thought, actually this change could make CI unable to catch error situations where tx is super slow or stuck. Maybe MIN_RX_PACKETS_CI should be a parameter instead of a define.

**Comment by matiaselo** [comment]
> But on second thought, actually this change could make CI unable to catch error situations where tx is super slow or stuck. Maybe MIN_RX_PACKETS_CI should be a parameter instead of a define.

I agree with this. We have similar checks also in several other examples (e.g. l2fwd, l2fwd_simple). For example `-C --ci-limit` should be available to use with all examples.

**Comment by nithind1988** [comment]
I agree. I'll drop this pull request for now as we have found another way to speed up our simulator and it seems to work fine.
I'll work on adding -C option in future if we again face similar issue.
Thanks

**Comment by matiaselo** [comment]
> I agree. I'll drop this pull request for now as we have found another way to speed up our simulator and it seems to work fine.
> I'll work on adding -C option in future if we again face similar issue.
> Thanks

OK, I'll close the PR then.

**Pull request closed without merging**
